experiment_name: 'tune_qm9_PNA_10000_hidden25_depth5'

multithreaded_seeds:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
pretrain_checkpoint: runs/OptimalTransportModel_file_loader_drugs_PNA_10000_hidden50_depth5_123_04-08_11-53-45/best_checkpoint.pt
transfer_layers:
  - gnn.
exclude_from_transfer:
  - batch_norm

dataset: 'ogbg-molbace'
num_epochs: 1000
batch_size: 32
log_iterations: 30
patience: 40
minimum_epochs: 120
loss_func: BCEWithLogitsLoss
required_data:
  - dgl_graph
  - targets
metrics:
  - rsquared
  - mean_predictor_loss
  - pearsonr


optimizer: Adam
optimizer_params:
  lr: 1.0e-3

scheduler_step_per_batch: False
lr_scheduler: WarmUpWrapper
lr_scheduler_params:
  warmup_steps: [700,700,350]
  interpolation: 'linear'
  # parameters of scheduler to run after warmup
  wrapped_scheduler: ReduceLROnPlateau
  factor: 0.5
  patience: 25
  min_lr: 1.0e-6
  mode: 'min'
  verbose: True



# Model parameters
model_type: 'PNARandom'
model_parameters:
  target_dim: 1
  hidden_dim: 25
  mid_batch_norm: True
  last_batch_norm: True
  readout_batchnorm: True
  # e^(log(forgetfulness ~0.001)/number of steps per epoch) = batch_norm_momentum   =>  e^(log(0.001)/100) = 0.970
  batch_norm_momentum: 0.1
  dropout: 0.0
  propagation_depth: 5
  aggregators:
    - mean
    - max
    - min
    - std
  scalers:
    - identity
    - amplification
    - attenuation
  readout_aggregators:
    - mean
    - sum
  pretrans_layers: 2
  posttrans_layers: 1
  residual: True




# continue training from checkpoint:
#checkpoint: runs/PNAReadout_2_layer_03-04_15-29-07/last_checkpoint.pt